### ISSUE TITLE
Error: spawn UNKNOWN when use command "tabnine.openconfig"

### ISSUE THREAD

**Issue by SouthAngel** [neoclide/coc-tabnine#37]
I have installed tabnine use command "CocInstall".
And i got this when using "CocCommand tabnine.openConfig".
```
2020-02-23T10:02:06.186 INFO (pid:9272) [plugin] - coc 0.0.74-bc017b02e6 initialized with node: v12.16.0

2020-02-23T10:02:06.310 INFO (pid:9272) [model-extension] - Loading info of coc-json.

2020-02-23T10:02:06.321 INFO (pid:9272) [model-fetch] - fetch: http://registry.npm.taobao.org/coc-json

2020-02-23T10:02:06.352 INFO (pid:9272) [model-extension] - Loading info of coc-pyls.

2020-02-23T10:02:06.354 INFO (pid:9272) [model-fetch] - fetch: http://registry.npm.taobao.org/coc-pyls

2020-02-23T10:02:06.354 INFO (pid:9272) [model-extension] - Loading info of coc-tabnine.

2020-02-23T10:02:06.358 INFO (pid:9272) [model-fetch] - fetch: http://registry.npm.taobao.org/coc-tabnine

2020-02-23T10:02:06.432 INFO (pid:9272) [model-extension] - Extension coc-json is up to date.

2020-02-23T10:02:06.483 INFO (pid:9272) [model-extension] - Extension coc-pyls is up to date.

2020-02-23T10:02:06.488 INFO (pid:9272) [model-extension] - Extension coc-tabnine is up to date.

2020-02-23T10:02:25.774 INFO (pid:9272) [completion-complete] - Results from: around

2020-02-23T10:02:28.467 INFO (pid:9272) [completion-complete] - Results from: around

2020-02-23T10:02:44.368 ERROR (pid:9272) [commands] - Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at Object.spawn (child_process.js:548:9)
    at TabNine.restartChild (C:\Users\SouthAngel\AppData\Local\coc\extensions\node_modules\coc-tabnine\lib\index.js:385:45)
    at C:\Users\SouthAngel\AppData\Local\coc\extensions\node_modules\coc-tabnine\lib\index.js:352:26
    at new Promise (<anonymous>)
    at TabNine.requestUnlocked (C:\Users\SouthAngel\AppData\Local\coc\extensions\node_modules\coc-tabnine\lib\index.js:349:16)
    at TabNine.<anonymous> (C:\Users\SouthAngel\AppData\Local\coc\extensions\node_modules\coc-tabnine\lib\index.js:336:35)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\SouthAngel\AppData\Local\coc\extensions\node_modules\coc-tabnine\lib\index.js:95:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by sQVe** [comment]
Try reinstalling. This is probably due to TabNine not creating the config file. You could also try TabNine::config so see if that fixes it.

**Comment by SouthAngel** [comment]
I have reinstalled and can not solve this problem.
Then i copy the file from .\AppData\Local\coc\extensions\coc-tabnine-data\binaries\2.3.4\x86_64-pc-windows-gnu\TabNine.exe to .\.vscode\extensions\tabnine.tabnine-vscode-2.2.2\binaries\2.3.4\x86_64-pc-windows-gnu\TabNine.exe, the command can working.

**Comment by sQVe** [comment]
Please provide full paths.

**Comment by SouthAngel** [comment]
Sorry..
I mean, replacing the executable file with what provided by vscode is useful.
Do these two files do the same thing?
Maybe the problem occur during the downloading?
Does some message can be show when download completed?  Success or fail..

**Comment by sQVe** [comment]
@SouthAngel The second path that you mentioned should not have anything to do with this plugin. Could you please provide the **full** paths?

**Comment by SouthAngel** [comment]
from

C:\Users\SouthAngel\ .vscode\extensions\tabnine.tabnine-vscode-2.2.2\binaries\2.3.4\x86_64-pc-windows-gnu\TabNine.exe

to

C:\Users\SouthAngel\AppData\Local\coc\extensions\coc-tabnine-data\binaries\2.3.4\x86_64-pc-windows-gnu\TabNine.exe

**Comment by sQVe** [comment]
It seems like the binary download is failing for you for some reason. Are you behind a proxy / VPN or something similar?

**Comment by SouthAngel** [comment]
No..

**Comment by rajprakharpatel** [comment]
### I replaced with JetBrains's tabnine plugin binary.

I had the exact error with neovim on windows10.
I didn't have vscode installed but had Pycharm so  I downloaded its tabnine plugin and then found it's binary and pasted it in place of the one that coc-tabnine downloads in the  ~\AppData\Local\coc\extensions\coc-tabnine-data\binaries\ folder.
After this, I could open tabnine's config and completions were also working.

Also, the JetBrains tabnine plugin downloaded the local model for tabnine completion.
