### ISSUE TITLE
neovim error

### ISSUE THREAD

**Issue by could-be** [neoclide/coc-tabnine#39]
```
[coc.nvim] error: Uncaught exception: Error: spawn /Users/admin/.config/coc/extensions/coc-tabnine-data/binaries/2.5.1/x86_64-apple-darwin/TabNine EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Press ENTER or type command to continue
```

I have TabNine installed local,  In my Neovim, it reports this code: 
What can  i do for it?

**Comment by sQVe** [comment]
I'm guessing that the permissions are wrong for the binary. What permissions does `TabNine` have?

**Comment by sQVe** [comment]
Closing as this has been inactive for some time.

**Comment by surmish** [comment]
Thanks @sQVe 
I faced the same issue. The permissions for TabNine were not quite correct:
```
prompt> v ~/.config/coc/extensions/coc-tabnine-data/binaries/2.8.1/x86_64-unknown-linux-musl/TabNine 
-rw-rw-r-- 1 ubuntu ubuntu 7732050 May  6 21:02 /home/ubuntu/.config/coc/extensions/coc-tabnine-data/binaries/2.8.1/x86_64-unknown-linux-musl/TabNine
```
chmod +x TabNine works fine.
