### ISSUE TITLE
coc-tabine does not support arm64.

### ISSUE THREAD

**Issue by mnnlkml** [neoclide/coc-tabnine#42]
## versions

vim version: NVIM v0.4.3
node version: v12.16.3
coc.nvim version: 0.0.75-89c0c2380b
term: xterm-256color
platform: android

## Messages
[coc.nvim] Error on active extension coc-tabnine: Error: Sorry, the architecture 'arm64' is not supported by TabNine.
    at Function.getArchAndPlatform (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:468:23)
    at Function.<anonymous> (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:421:45)
    at Generator.next (<anonymous>)
    at fulfilled (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:95:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
8 fewer lines

8 more lines; before #1  3 seconds ago

## CocOpenLog info

2020-04-30T09:22:50.851 INFO (pid:5843) [services] - registered service "eslint"
2020-04-30T09:22:52.107 INFO (pid:5843) [model-fetch] - fetch: https://update.tabnine.com/version
2020-04-30T09:22:52.365 INFO (pid:5843) [plugin] - coc 0.0.75-89c0c2380b initialized with node: v12.16.3
2020-04-30T09:22:53.657 ERROR (pid:5843) [extensions] - Error: Sorry, the architecture 'arm64' is not supported by TabNine.
    at Function.getArchAndPlatform (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:468:23)
    at Function.<anonymous> (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:421:45)
    at Generator.next (<anonymous>)
    at fulfilled (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:95:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by chemzqm** [comment]
Fixed with latest coc-tabnine
