### ISSUE TITLE
tabnine.openConfig error: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by surmish** [neoclide/coc-tabnine#44]
Here are the error messages 
CocInfo:
```
## versions   
              
vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
node version: v10.19.0
coc.nvim version: 0.0.78-57637bb44c
term: dumb    
platform: linux
              
## Output channel: vimlsp
              
events.js:174 
      throw er; // Unhandled 'error' event
      ^       
              
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:636:16)
    at t.process.on.i.pipe.subscribe.process.send.msglog [as _next] (/home/ubuntu/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:49:146271)
    at t.__tryOrUnsub (/home/ubuntu/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:34:62809)
    at t.next (/home/ubuntu/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:34:61916)
    at t._next (/home/ubuntu/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:34:60946)
    at t.next (/home/ubuntu/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:34:60617)
    at t._next (/home/ubuntu/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:49:55668)
    at t.next (/home/ubuntu/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:34:60617)                                                                                                                                               
    at t.notifyNext (/home/ubuntu/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:49:45139)
    at t._next (/home/ubuntu/.config/coc/extensions/node_modules/coc-vimlsp/out/scan.js:49:40619)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:640:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

vim version:
```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +cindent           +cursorshape       +file_in_path      +jumplist          +mksession         +mouse_xterm       +printer           +sound             +terminal          +virtualedit       -xim
+arabic            -clientserver      +dialog_con        +find_in_path      +keymap            +modify_fname      +multi_byte        +profile           +spell             +terminfo          +visual            -xpm
+autocmd           -clipboard         +diff              +float             +lambda            +mouse             +multi_lang        -python            +startuptime       +termresponse      +visualextra       -xsmp
+autochdir         +cmdline_compl     +digraphs          +folding           +langmap           -mouseshape        -mzscheme          +python3           +statusline        +textobjects       +viminfo           -xterm_clipboard
-autoservername    +cmdline_hist      -dnd               -footer            +libcall           +mouse_dec         +netbeans_intg     +quickfix          -sun_workshop      +textprop          +vreplace          -xterm_save
-balloon_eval      +cmdline_info      -ebcdic            +fork()            +linebreak         +mouse_gpm         +num64             +reltime           +syntax            +timers            +wildignore
+balloon_eval_term +comments          +emacs_tags        +gettext           +lispindent        -mouse_jsbterm     +packages          +rightleft         +tag_binary        +title             +wildmenu
-browse            +conceal           +eval              -hangul_input      +listcmds          +mouse_netterm     +path_extra        -ruby              -tag_old_static    -toolbar           +windows
++builtin_terms    +cryptv            +ex_extra          +iconv             +localmap          +mouse_sgr         -perl              +scrollbind        -tag_any_white     +user_commands     +writebackup
+byte_offset       +cscope            +extra_search      +insert_expand     -lua               -mouse_sysmouse    +persistent_undo   +signs             -tcl               +vartabs           -X11
+channel           +cursorbind        -farsi             +job               +menu              +mouse_urxvt       +postscript        +smartindent       +termguicolors     +vertsplit         -xfontset
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-iU6mZD/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthre
ad -ldl -lutil -lm -lm
```

**Comment by chemzqm** [comment]
Could be issue with your coc-vimlsp, but I can't reproduce.

**Comment by surmish** [comment]
Do I need to purchase tabnine license? I have not installed tabnine through any other means.

**Comment by chemzqm** [comment]
It doesn't related to tabnine.

**Comment by surmish** [comment]
Is there any other way to install tabnine with coc ?

**Comment by surmish** [comment]
Hi @chemzqm, the problem was 2 fold: I had to install the electron pre-built binaries using
`npm install electron --save-dev`. I came across this error here: https://github.com/electron/electron-quick-start/issues/30#issuecomment-263447608

which led to another error discussed here: https://github.com/neoclide/coc-tabnine/issues/39
I was able to resolve it by changing permissions on `TabNine` binary.
