### ISSUE TITLE
TypeError: (intermediate value).trim is not a function

### ISSUE THREAD

**Issue by nzlov** [neoclide/coc-tabnine#50]
## versions

vim version: NVIM v0.4.4
node version: v14.15.1
coc.nvim version: 0.0.79-3658eda4fa
coc.nvim directory: /Users/nzlov/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin
coc-tabnine: 1.2.2
## Log of coc.nvim
```
2020-11-27T17:27:45.126 INFO (pid:64216) [services] - registered service "highlight"
2020-11-27T17:27:45.178 INFO (pid:64216) [language-client-index] - highlight started with 64219
2020-11-27T17:27:45.231 INFO (pid:64216) [model-fetch] - Using proxy http://127.0.0.1:1087/ from system environment for update.tabnine.com:
2020-11-27T17:27:45.687 WARN (pid:64216) [attach] - Plugin not ready when received "highlight" []
2020-11-27T17:27:46.762 ERROR (pid:64216) [extensions] - Error on active extension coc-tabnine: TypeError: (intermediate value).trim is not a function
    at Function.<anonymous> (/Users/nzlov/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:420:92)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nzlov/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:95:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) TypeError: (intermediate value).trim is not a function
    at Function.<anonymous> (/Users/nzlov/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:420:92)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nzlov/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:95:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-11-27T17:27:46.768 INFO (pid:64216) [plugin] - coc.nvim 0.0.79-3658eda4fa initialized with node: v14.15.1 after 1775ms
```

**Comment by MrAdityaAlok** [comment]
Yes, the same problem with me.😭
